name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.1
  - pip
  - pip:
    - mlflow==2.16.0
    - xgboost==2.1.1
    - scikit-learn==1.5.1
    - pandas==2.2.2
    - numpy==1.26.4